package be;

import org.thunderdog.challegram.Log;
import org.thunderdog.challegram.R;

public final class g extends e {
    public g() {
        super(2);
    }

    @Override
    public float d(int i10) {
        switch (i10) {
            case R.id.theme_property_dark:
            case R.id.theme_property_parentTheme:
            case R.id.theme_property_shadowDepth:
            case R.id.theme_property_wallpaperUsageId:
                return 1.0f;
            default:
                return super.d(i10);
        }
    }

    @Override
    public int e(int i10) {
        switch (i10) {
            case R.id.theme_color_attachContact:
            case R.id.theme_color_attachFile:
            case R.id.theme_color_attachInlineBot:
            case R.id.theme_color_attachLocation:
            case R.id.theme_color_attachPhoto:
            case R.id.theme_color_badgeMutedText:
            case R.id.theme_color_badgeText:
            case R.id.theme_color_bubbleIn_background:
            case R.id.theme_color_bubbleOut_background:
            case R.id.theme_color_chatKeyboardButton:
            case R.id.theme_color_headerBackground:
            case R.id.theme_color_headerBarCallMuted:
            case R.id.theme_color_headerLightBackground:
            case R.id.theme_color_inlineContentActive:
            case R.id.theme_color_iv_preBlockBackground:
            case R.id.theme_color_iv_textCodeBackground:
            case R.id.theme_color_iv_textCodeBackgroundPressed:
            case R.id.theme_color_messageSwipeBackground:
            case R.id.theme_color_notification:
            case R.id.theme_color_notificationPlayer:
            case R.id.theme_color_passcode:
            case R.id.theme_color_unread:
                return -14606047;
            case R.id.theme_color_attachText:
            case R.id.theme_color_avatarArchive:
            case R.id.theme_color_avatarArchivePinned:
            case R.id.theme_color_avatarInactive:
            case R.id.theme_color_avatarInactive_big:
            case R.id.theme_color_avatarReplies:
            case R.id.theme_color_avatarReplies_big:
            case R.id.theme_color_avatarSavedMessages:
            case R.id.theme_color_avatarSavedMessages_big:
            case R.id.theme_color_avatar_content:
            case R.id.theme_color_badgeFailed:
            case R.id.theme_color_badgeFailedText:
            case R.id.theme_color_black:
            case R.id.theme_color_bubbleOut_chatNegativeFilling:
            case R.id.theme_color_bubbleOut_chatNegativeFillingContent:
            case R.id.theme_color_bubble_button:
            case R.id.theme_color_bubble_buttonRipple:
            case R.id.theme_color_bubble_buttonText:
            case R.id.theme_color_bubble_buttonText_noWallpaper:
            case R.id.theme_color_bubble_chatBackground:
            case R.id.theme_color_bubble_date:
            case R.id.theme_color_bubble_dateText:
            case R.id.theme_color_bubble_dateText_noWallpaper:
            case R.id.theme_color_bubble_mediaOverlay:
            case R.id.theme_color_bubble_mediaOverlayText:
            case R.id.theme_color_bubble_mediaReply:
            case R.id.theme_color_bubble_mediaReplyText:
            case R.id.theme_color_bubble_mediaReplyText_noWallpaper:
            case R.id.theme_color_bubble_mediaTime:
            case R.id.theme_color_bubble_mediaTimeText:
            case R.id.theme_color_bubble_mediaTimeText_noWallpaper:
            case R.id.theme_color_bubble_mediaTime_noWallpaper:
            case R.id.theme_color_bubble_overlayText:
            case R.id.theme_color_bubble_overlayText_noWallpaper:
            case R.id.theme_color_bubble_overlay_noWallpaper:
            case R.id.theme_color_bubble_unread:
            case R.id.theme_color_bubble_unreadText:
            case R.id.theme_color_bubble_unreadText_noWallpaper:
            case R.id.theme_color_caption_textLink:
            case R.id.theme_color_caption_textLinkPressHighlight:
            case R.id.theme_color_circleButtonNegative:
            case R.id.theme_color_circleButtonNegativeIcon:
            case R.id.theme_color_circleButtonNewChannel:
            case R.id.theme_color_circleButtonNewChannelIcon:
            case R.id.theme_color_circleButtonNewChat:
            case R.id.theme_color_circleButtonNewChatIcon:
            case R.id.theme_color_circleButtonNewGroup:
            case R.id.theme_color_circleButtonNewGroupIcon:
            case R.id.theme_color_circleButtonNewSecret:
            case R.id.theme_color_circleButtonNewSecretIcon:
            case R.id.theme_color_circleButtonPositive:
            case R.id.theme_color_circleButtonPositiveIcon:
            case R.id.theme_color_circleButtonRegularIcon:
            case R.id.theme_color_circleButtonThemeIcon:
            case R.id.theme_color_confettiBlue:
            case R.id.theme_color_confettiCyan:
            case R.id.theme_color_confettiGreen:
            case R.id.theme_color_confettiPurple:
            case R.id.theme_color_confettiRed:
            case R.id.theme_color_confettiYellow:
            case R.id.theme_color_drawer:
            case R.id.theme_color_drawerText:
            case R.id.theme_color_fileGreen:
            case R.id.theme_color_fileRed:
            case R.id.theme_color_fileYellow:
            case R.id.theme_color_fillingNegative:
            case R.id.theme_color_fillingPositiveContent:
            case R.id.theme_color_headerIcon:
            case R.id.theme_color_headerPickerBackground:
            case R.id.theme_color_headerPickerText:
            case R.id.theme_color_headerRemoveBackground:
            case R.id.theme_color_headerRemoveBackgroundHighlight:
            case R.id.theme_color_headerTabActive:
            case R.id.theme_color_headerTabActiveText:
            case R.id.theme_color_headerTabInactiveText:
            case R.id.theme_color_headerText:
            case R.id.theme_color_iconNegative:
            case R.id.theme_color_iconPositive:
            case R.id.theme_color_inputNegative:
            case R.id.theme_color_inputPositive:
            case R.id.theme_color_ivHeader:
            case R.id.theme_color_ivHeaderIcon:
            case R.id.theme_color_iv_chatLinkOverlayBackground:
            case R.id.theme_color_iv_textMarkedBackground:
            case R.id.theme_color_ledBlue:
            case R.id.theme_color_ledCyan:
            case R.id.theme_color_ledGreen:
            case R.id.theme_color_ledOrange:
            case R.id.theme_color_ledPink:
            case R.id.theme_color_ledPurple:
            case R.id.theme_color_ledRed:
            case R.id.theme_color_ledWhite:
            case R.id.theme_color_ledYellow:
            case R.id.theme_color_messageNegativeLine:
            case R.id.theme_color_messageSwipeContent:
            case R.id.theme_color_passcodeIcon:
            case R.id.theme_color_passcodeText:
            case R.id.theme_color_photoHighlightTint1:
            case R.id.theme_color_photoHighlightTint2:
            case R.id.theme_color_photoHighlightTint3:
            case R.id.theme_color_photoHighlightTint4:
            case R.id.theme_color_photoHighlightTint5:
            case R.id.theme_color_photoHighlightTint6:
            case R.id.theme_color_photoHighlightTint7:
            case R.id.theme_color_photoShadowTint1:
            case R.id.theme_color_photoShadowTint2:
            case R.id.theme_color_photoShadowTint3:
            case R.id.theme_color_photoShadowTint4:
            case R.id.theme_color_photoShadowTint5:
            case R.id.theme_color_photoShadowTint6:
            case R.id.theme_color_photoShadowTint7:
            case R.id.theme_color_playerCoverIcon:
            case R.id.theme_color_sectionedScrollBar:
            case R.id.theme_color_sectionedScrollBarActive:
            case R.id.theme_color_sectionedScrollBarActiveContent:
            case R.id.theme_color_snackbarUpdateAction:
            case R.id.theme_color_snackbarUpdateText:
            case R.id.theme_color_statusBarContent:
            case R.id.theme_color_statusBarLegacy:
            case R.id.theme_color_statusBarLegacyContent:
            case R.id.theme_color_textNegative:
            case R.id.theme_color_themeBlue:
            case R.id.theme_color_themeClassic:
            case R.id.theme_color_themeCyan:
            case R.id.theme_color_themeGreen:
            case R.id.theme_color_themeNightBlue:
            case R.id.theme_color_themeOrange:
            case R.id.theme_color_themePink:
            case R.id.theme_color_themeRed:
            case R.id.theme_color_themeWhiteBlack:
            case R.id.theme_color_togglerNegative:
            case R.id.theme_color_togglerNegativeBackground:
            case R.id.theme_color_togglerNegativeContent:
            case R.id.theme_color_tooltip:
            case R.id.theme_color_tooltip_text:
            case R.id.theme_color_transparentEditor:
            case R.id.theme_color_videoSliderActive:
            case R.id.theme_color_videoSliderInactive:
            default:
                return super.e(i10);
            case R.id.theme_color_avatarBlue:
            case R.id.theme_color_avatarBlue_big:
            case R.id.theme_color_nameBlue:
                return -8338950;
            case R.id.theme_color_avatarCyan:
            case R.id.theme_color_avatarCyan_big:
            case R.id.theme_color_nameCyan:
                return -9648164;
            case R.id.theme_color_avatarGreen:
            case R.id.theme_color_avatarGreen_big:
            case R.id.theme_color_bubbleOut_messageAuthorPsa:
            case R.id.theme_color_messageAuthorPsa:
            case R.id.theme_color_nameGreen:
                return -7551634;
            case R.id.theme_color_avatarOrange:
            case R.id.theme_color_avatarOrange_big:
            case R.id.theme_color_nameOrange:
                return -745623;
            case R.id.theme_color_avatarPink:
            case R.id.theme_color_avatarPink_big:
            case R.id.theme_color_namePink:
                return -1998420;
            case R.id.theme_color_avatarRed:
            case R.id.theme_color_avatarRed_big:
            case R.id.theme_color_nameRed:
                return -1017483;
            case R.id.theme_color_avatarViolet:
            case R.id.theme_color_avatarViolet_big:
            case R.id.theme_color_nameViolet:
                return -4410375;
            case R.id.theme_color_avatarYellow:
            case R.id.theme_color_avatarYellow_big:
            case R.id.theme_color_nameYellow:
                return -407478;
            case R.id.theme_color_background:
            case R.id.theme_color_bubbleIn_outline:
            case R.id.theme_color_bubbleIn_separator:
            case R.id.theme_color_bubbleOut_chatCorrectChosenFillingContent:
            case R.id.theme_color_bubbleOut_chatCorrectFillingContent:
            case R.id.theme_color_bubbleOut_chatNeutralFillingContent:
            case R.id.theme_color_bubbleOut_outline:
            case R.id.theme_color_bubble_chatSeparator:
            case R.id.theme_color_chatKeyboard:
            case R.id.theme_color_chatSeparator:
            case R.id.theme_color_checkContent:
            case R.id.theme_color_circleButtonActiveIcon:
            case R.id.theme_color_controlContent:
            case R.id.theme_color_iv_chatLinkBackground:
            case R.id.theme_color_messageCorrectChosenFillingContent:
            case R.id.theme_color_messageCorrectFillingContent:
            case R.id.theme_color_messageNegativeLineContent:
            case R.id.theme_color_messageNeutralFillingContent:
            case R.id.theme_color_promoContent:
            case R.id.theme_color_separator:
            case R.id.theme_color_shareSeparator:
            case R.id.theme_color_togglerPositiveContent:
                return -16777216;
            case R.id.theme_color_background_icon:
            case R.id.theme_color_background_text:
            case R.id.theme_color_background_textLight:
            case R.id.theme_color_bubbleIn_time:
            case R.id.theme_color_bubbleOut_progress:
            case R.id.theme_color_bubbleOut_separator:
            case R.id.theme_color_bubbleOut_time:
            case R.id.theme_color_circleButtonChatIcon:
            case R.id.theme_color_circleButtonOverlayIcon:
            case R.id.theme_color_icon:
            case R.id.theme_color_iv_caption:
            case R.id.theme_color_iv_icon:
            case R.id.theme_color_iv_pageAuthor:
            case R.id.theme_color_iv_pageFooter:
            case R.id.theme_color_textLight:
            case R.id.theme_color_textPlaceholder:
                return -6250336;
            case R.id.theme_color_badge:
            case R.id.theme_color_bubbleIn_progress:
            case R.id.theme_color_bubbleIn_text:
            case R.id.theme_color_bubbleOut_chatCorrectChosenFilling:
            case R.id.theme_color_bubbleOut_chatCorrectFilling:
            case R.id.theme_color_bubbleOut_chatVerticalLine:
            case R.id.theme_color_bubbleOut_inlineIcon:
            case R.id.theme_color_bubbleOut_inlineOutline:
            case R.id.theme_color_bubbleOut_inlineText:
            case R.id.theme_color_bubbleOut_text:
            case R.id.theme_color_bubbleOut_ticks:
            case R.id.theme_color_bubbleOut_ticksRead:
            case R.id.theme_color_chatListAction:
            case R.id.theme_color_chatListVerify:
            case R.id.theme_color_chatSendButton:
            case R.id.theme_color_checkActive:
            case R.id.theme_color_circleButtonActive:
            case R.id.theme_color_controlActive:
            case R.id.theme_color_headerButtonIcon:
            case R.id.theme_color_headerLightIcon:
            case R.id.theme_color_headerLightText:
            case R.id.theme_color_iconActive:
            case R.id.theme_color_inlineIcon:
            case R.id.theme_color_inlineOutline:
            case R.id.theme_color_inlineText:
            case R.id.theme_color_inputActive:
            case R.id.theme_color_introSectionActive:
            case R.id.theme_color_iv_blockQuoteLine:
            case R.id.theme_color_iv_header:
            case R.id.theme_color_iv_pageTitle:
            case R.id.theme_color_iv_text:
            case R.id.theme_color_iv_textCode:
            case R.id.theme_color_iv_textMarked:
            case R.id.theme_color_iv_textReference:
            case R.id.theme_color_messageCorrectChosenFilling:
            case R.id.theme_color_messageCorrectFilling:
            case R.id.theme_color_messageVerticalLine:
            case R.id.theme_color_notificationLink:
            case R.id.theme_color_online:
            case R.id.theme_color_playerButton:
            case R.id.theme_color_profileSectionActive:
            case R.id.theme_color_profileSectionActiveContent:
            case R.id.theme_color_progress:
            case R.id.theme_color_promo:
            case R.id.theme_color_sliderActive:
            case R.id.theme_color_text:
            case R.id.theme_color_textNeutral:
            case R.id.theme_color_themeBlackWhite:
            case R.id.theme_color_ticks:
            case R.id.theme_color_ticksRead:
            case R.id.theme_color_togglerActive:
            case R.id.theme_color_togglerPositive:
            case R.id.theme_color_unreadText:
                return -1;
            case R.id.theme_color_badgeMuted:
            case R.id.theme_color_controlInactive:
            case R.id.theme_color_nameInactive:
            case R.id.theme_color_themeNightBlack:
            case R.id.theme_color_togglerInactiveBackground:
                return -9803158;
            case R.id.theme_color_bubbleIn_pressed:
            case R.id.theme_color_bubbleOut_pressed:
                return Log.TAG_TDLIB_FILES;
            case R.id.theme_color_bubbleIn_textLink:
            case R.id.theme_color_bubbleOut_messageAuthor:
            case R.id.theme_color_bubbleOut_textLink:
            case R.id.theme_color_iv_textLink:
            case R.id.theme_color_iv_textMarkedLink:
            case R.id.theme_color_messageAuthor:
            case R.id.theme_color_textLink:
            case R.id.theme_color_textSearchQueryHighlight:
            case R.id.theme_color_tooltip_textLink:
                return -8750470;
            case R.id.theme_color_bubbleIn_textLinkPressHighlight:
            case R.id.theme_color_bubbleOut_textLinkPressHighlight:
            case R.id.theme_color_iv_textLinkPressHighlight:
            case R.id.theme_color_iv_textMarkedLinkPressHighlight:
            case R.id.theme_color_seekReady:
            case R.id.theme_color_textLinkPressHighlight:
            case R.id.theme_color_tooltip_textLinkPressHighlight:
                return 1081768570;
            case R.id.theme_color_bubbleOut_file:
            case R.id.theme_color_file:
            case R.id.theme_color_fileAttach:
            case R.id.theme_color_inputInactive:
                return -12961222;
            case R.id.theme_color_bubbleOut_waveformActive:
            case R.id.theme_color_waveformActive:
                return -3487030;
            case R.id.theme_color_bubbleOut_waveformInactive:
            case R.id.theme_color_fillingPositive:
            case R.id.theme_color_waveformInactive:
                return -13619152;
            case R.id.theme_color_bubble_buttonRipple_noWallpaper:
            case R.id.theme_color_bubble_button_noWallpaper:
                return 547397792;
            case R.id.theme_color_bubble_date_noWallpaper:
            case R.id.theme_color_bubble_mediaReply_noWallpaper:
            case R.id.theme_color_bubble_overlay:
            case R.id.theme_color_bubble_unread_noWallpaper:
                return 1084268704;
            case R.id.theme_color_bubble_messageCheckOutline:
                return -1381654;
            case R.id.theme_color_bubble_messageCheckOutlineNoWallpaper:
                return -9671572;
            case R.id.theme_color_bubble_messageSelection:
            case R.id.theme_color_iv_textReferenceOutlinePressed:
                return 553648127;
            case R.id.theme_color_bubble_messageSelectionNoWallpaper:
                return 452984831;
            case R.id.theme_color_chatBackground:
            case R.id.theme_color_filling:
                return -15461356;
            case R.id.theme_color_chatListIcon:
            case R.id.theme_color_chatListMute:
                return -9341316;
            case R.id.theme_color_circleButtonChat:
            case R.id.theme_color_circleButtonOverlay:
            case R.id.theme_color_circleButtonRegular:
            case R.id.theme_color_circleButtonTheme:
            case R.id.theme_color_headerButton:
            case R.id.theme_color_overlayFilling:
            case R.id.theme_color_seekEmpty:
                return -14803426;
            case R.id.theme_color_fillingPressed:
                return -14671840;
            case R.id.theme_color_headerBarCallActive:
                return -12500671;
            case R.id.theme_color_headerBarCallIncoming:
                return -8355712;
            case R.id.theme_color_headerPlaceholder:
                return 285212671;
            case R.id.theme_color_iconLight:
                return -11248797;
            case R.id.theme_color_introSection:
                return -8289919;
            case R.id.theme_color_iv_blockQuote:
                return -197380;
            case R.id.theme_color_iv_pageSubtitle:
                return -4539718;
            case R.id.theme_color_iv_pullQuote:
                return -394759;
            case R.id.theme_color_iv_separator:
                return -12303292;
            case R.id.theme_color_iv_textReferenceBackground:
                return 720564978;
            case R.id.theme_color_iv_textReferenceBackgroundPressed:
                return 820044000;
            case R.id.theme_color_iv_textReferenceOutline:
            case R.id.theme_color_tooltip_outline:
                return 1157627903;
            case R.id.theme_color_messageSelection:
                return 721420287;
            case R.id.theme_color_notificationSecure:
            case R.id.theme_color_textSecure:
                return -8854914;
            case R.id.theme_color_placeholder:
                return 218103807;
            case R.id.theme_color_playerButtonActive:
                return -3355444;
            case R.id.theme_color_playerCoverPlaceholder:
                return -15658735;
            case R.id.theme_color_previewBackground:
                return 1879048192;
            case R.id.theme_color_seekDone:
                return -4144960;
            case R.id.theme_color_sliderInactive:
                return -13553359;
            case R.id.theme_color_snackbarUpdate:
                return -13750738;
            case R.id.theme_color_statusBar:
                return Log.TAG_TDLIB_OPTIONS;
            case R.id.theme_color_textSelectionHighlight:
                return 1442840575;
            case R.id.theme_color_togglerActiveBackground:
            case R.id.theme_color_togglerPositiveBackground:
                return -7697782;
            case R.id.theme_color_togglerInactive:
                return -5723992;
        }
    }
}
